# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
labels:
  org.opencontainers.image.title: "Home Assistant Addon: Minecraft Server
  org.opencontainers.image.description: "This addon runs a minecraft server Java  The 1.7.10 Pack edition. It can be fully configured in the UI."
  org.opencontainers.image.source: "https://github.com/RobertVPettigrew/Java-MC-Homeasistant-Addon"
  org.opencontainers.image.licenses: "MIT License"
args:
  TEMPIO_VERSION: "2021.09.0"
